/*
 * Copyright (c) 2025 Atos Spain S.A. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Conformance API v3
 * EBSI WCT v3
 *
 * OpenAPI spec version: 3.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.eviden.bds.rd.uself.agent.models

import kotlinx.serialization.Serializable

/**
 * A Problem Details object (RFC 7807)
 * @param type An absolute URI that identifies the problem type.
 * When dereferenced, it SHOULD provide human-readable documentation for the problem type.
 * @param title A short summary of the problem type.
 * @param status The HTTP status code generated by the origin server for this occurrence of the problem.
 * @param detail A human-readable explanation specific to this occurrence of the problem.
 * @param instance An absolute URI that identifies the specific occurrence of the problem.
 * It may or may not yield further information if dereferenced.
 */
@Serializable
data class Problem(

    /* An absolute URI that identifies the problem type.
    When dereferenced, it SHOULD provide human-readable documentation for the problem type.  */
    val type: String? = null,
    /* A short summary of the problem type. */
    val title: String? = null,
    /* The HTTP status code generated by the origin server for this occurrence of the problem.  */
    val status: String? = null,
    /* A human-readable explanation specific to this occurrence of the problem.  */
    val detail: String? = null,
    /* An absolute URI that identifies the specific occurrence of the problem.
    It may or may not yield further information if dereferenced.  */
    val instance: String? = null
)
